name: Build Semantic Scholar JSON

on:
  schedule:
    - cron: "0 4 * * 1"   # Every Monday 04:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: python -m pip install --upgrade pip requests

      - name: Generate member publications JSON
        run: python tools/s2_to_member_json.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add members/**/publications.json
            git commit -m "chore: update publications.json from Semantic Scholar"
            git push
          else
            echo "No changes."
          fi
