name: Build Semantic Scholar JSON

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Generate member publications JSON
        run: python tools/s2_to_member_json.py

      - name: Build homepage highlights (OG images + S2 figures fallback)
        env:
          UNPAYWALL_EMAIL: ${{ secrets.UNPAYWALL_EMAIL }}  # optional but helpful
        run: python tools/build_highlights.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add members/**/publications.json data/highlights.auto.json
            git commit -m "chore: pubs + highlights (og + S2 figures)"
            git push
          else
            echo "No changes."
          fi
